language: scala
script:
 - git config user.email ${GITHUB_EMAIL}
 - git config user.name ${GITHUB_USER}
 - git remote set-url origin https://${GITHUB_TOKEN}@github.com/oliverlockwood/sbt-release-tags-only.git
 - sbt release
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  only:
  - master
